project:
  type: website

website:
  title: "Curso de Estadística (Inecol)"
  favicon: images/bar-chart.png
  navbar:
    right:
      - text: "Algo más"
        menu:
          - about.qmd
          - presentaciones.qmd
          - ejercicios.qmd
      - icon: github
        href: https://github.com/equihuam/M3-2024_causalidad

format:
  html:
    theme: sketchy
    css: styles.css

editor: source
execute: 
  freeze: true
