project:
  type: website

website:
  title: "M3 - Curso de Estadística (Inecol)"
  favicon: images/bar-chart.png
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/equihuam/M3-2024_causalidad
format:
  html:
    theme: sketchy
    css: styles.css

editor: visual

